# Build settings
[build]
  # The command to build your project (e.g., npm run build)
  command = "npm run build"

  # The directory where the built files are located
  publish = "build"

  # The version of Node.js to use for building (ensure it matches your local version)
  node_version = "16"

# Environment variables
[build.environment]
  # Set NODE_OPTIONS to --legacy-peer-deps
  NODE_OPTIONS = "--legacy-peer-deps"

  # Set the environment variable for the desired React version
  REACT_APP_VERSION = "18.2.0"
